# Generated by Django 5.1.4 on 2024-12-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='noteContent',
            field=models.CharField(max_length=300),
        ),
    ]
