# Generated by Django 5.1.4 on 2024-12-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_notecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='noteImage',
            field=models.ImageField(upload_to='notes/'),
        ),
    ]
