# Generated by Django 5.1.4 on 2024-12-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_noteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='noteImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
